export const CLEAR_MUSIC_LIST = 'CLEAR_MUSIC_LIST'

export const SET_RANK_LIST = 'SET_RANK_LIST'

export const SET_RECOMMENDS = 'SET_RECOMMEND_LIST'

export const CLEAR_RECOMMENDS = 'CLEAR_RECOMMEND_LIST'

export const SET_ARTISTS = 'SET_ARTIST_LIST'

export const CLEAR_ARTISTS = 'CLEAR_ARTIST_LIST'

export const SET_HOST_KEYWORDS = 'SET_HOST_KEYWORDS'

export const ADD_SEARCH_HISTORY = 'ADD_SEARCH_HISTORY'

export const DELETE_SEARCH_HISTORY = 'DELETE_SEARCH_HISTORY'

export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY'

export const SET_SEARCH_SONGS = 'SET_SEARCH_SONGS'

export const CLEAR_SEARCH_SONGS = 'CLEAR_SEARCH_SONGS'

export const SET_PLAYLIST_DETAIL = 'SET_PLAYLIST_DETAIL'

export const SET_ARTIST_TOP_LIST = 'SET_ARTIST_TOP_LIST'

export const CLEAR_ARTIST_TOP_LIST = 'CLEAR_ARTIST_TOP_LIST'

export const CLEAR_PLAYLIST_DETAIL = 'CLEAR_PLAYLIST_DETAIL'

export const SET_RANK_SONG_DETAIL = 'SET_RANK_SONG_DETAIL'

export const CLEAR_RANK_SONG_DETAIL = 'CLEAR_RANK_SONG_DETAIL'

export const SET_IS_PLAYING = 'SET_IS_PLAYING'

export const SET_MINI_MODE = 'SET_MINI_MODE'

export const SET_MUSIC_LIST ='SET_MUSIC_LIST'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_HISTORY_PLAYED_LIST = 'SET_HISTORY_PLAYED_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_MUSIC = 'SET_CURRENT_MUSIC'

export const SET_CURRENT_TIME = 'SET_CURRENT_TIME'